### ISSUE TITLE
[Bug]: Non-parsable parameter value received from eufy cloud

### ISSUE THREAD

**Issue by Lordbooker** [bropat/ioBroker.eusec#381] opened 2023-10-04 10:02 UTC
### Adapter version

1.1.2

### JS-Controller version

5.0.12

### Node version

18.17.1

### Operating System type

Docker

### Operating system version

???

### Describe the bug

JSON parse error [{"error":{"message":"SyntaxError: Unexpected end of JSON input","stacktrace":"SyntaxError: Unexpected end of JSON input\n at JSON.parse (<anonymous>)\n at parseJSON (/opt/iobroker/node_modules/eufy-security-client/build/utils.js:154:21)\n at ParameterHelper.readValue (/opt/iobroker/node_modules/eufy-security-client/build/http/parameter.js:50:63)\n at Camera.updateRawProperty (/opt/iobroker/node_modules/eufy-security-client/build/http/device.js:127:57)\n at /opt/iobroker/node_modules/eufy-security-client/build/http/device.js:54:22\n at Array.forEach (<anonymous>)\n at Camera.update (/opt/iobroker/node_modules/eufy-security-client/build/http/device.js:53:35)\n at EufySecurity.updateDevice (/opt/iobroker/node_modules/eufy-security-client/build/eufysecurity.js:344:44)\n at EufySecurity.handleDevices (/opt/iobroker/node_modules/eufy-security-client/build/eufysecurity.js:560:22)\n at HTTPApi.<anonymous> (/opt/iobroker/node_modules/eufy-security-client/build/eufysecurity.js:167:50)"},"data":"{\"r"}]

### To reproduce

2. Click on '...'

**Comment by firebowl** [comment] 2023-10-05 05:25
Same problem here. It is flooding my ioBroker log.

**Comment by bropat** [comment] 2023-10-06 15:23
Duplicate of #374

**Closed by bropat** 2023-10-06 15:23 UTC
Labels: bug

**Comment by duylong** [comment] 2023-10-23 09:47
Same problem with 1.6.4. I downgraded to 1.6.0 and the problem disappeared for me.
Try to see if anyone has the problem.

Home base 2
Cam model : T8142
