### ISSUE TITLE
CMD_SDINFO_EX failed with error: undefined (-148)

### ISSUE THREAD

**Issue by sansonifabio** [bropat/ioBroker.eusec#379] opened 2023-09-19 04:32 UTC
### Adapter version

1.1.2 und 1.2.1

### JS-Controller version

 5.0.12

### Node version

18.17.1 und 18.18.0

### Operating System type

Linux

### Operating system version

Bookworm Debian

### Describe the bug

Hello Bropat,
This night Eufy made updates to the home bases and yesterday also to the app 4.7.3_1319.
When I go to the event list on my cell phone, the error messages appear in the ioBroker.
Otherwise the adapter works correctly.

Greetings
Fabio

---------------------------------------------------------------------------------------------------------------------

Hallo Bropat,
diese Nacht hat Eufy Updates gemacht an den Homebases und gestern auch an der App 4.7.3_1319. 
Wenn ich an meinen Handy in die Ereignissliste gehe kommen die Fehlermeldumngen im ioBroker. 
Sonst arbeitet der Adapter korrekt.

Grüße
Fabio

### To reproduce

2. Click on '...'

### Screenshots & Logfiles

eusec.0 | 2023-09-19 06:30:00.534 | error | Station: T8030P232242039F command CMD_SDINFO_EX failed with error: undefined (-148)
-- | -- | -- | --
eusec.0 | 2023-09-19 06:30:00.530 | error | Station: T8030P23224511EB command CMD_SDINFO_EX failed with error: undefined (-148)
eusec.0 | 2023-09-19 06:30:00.507 | error | Station: T8030P232245105A command CMD_SDINFO_EX failed with error: undefined (-148)
eusec.0 | 2023-09-19 06:30:00.479 | error | Station: T8030P2322481D9C command CMD_SDINFO_EX failed with error: undefined (-148)
eusec.0 | 2023-09-19 06:29:03.711 | error | Station: T8030P23224511EB command CMD_SDINFO_EX failed with error: undefined (-148)
eusec.0 | 2023-09-19 06:29:03.687 | error | Station: T8030P232242039F command CMD_SDINFO_EX failed with error: undefined (-148)
eusec.0 | 2023-09-19 06:29:03.661 | error | Station: T8030P232245105A command CMD_SDINFO_EX failed with error: undefined (-148)
eusec.0 | 2023-09-19 06:29:03.631 | error | Station: T8030P2322481D9C command CMD_SDINFO_EX failed with error: undefined (-148)

</body>
</html>

**Comment by RamsesIoBroker** [comment] 2023-09-20 07:56
Ich habe die gleichen Fehlermeldungen, selbes System, aber JS-Controller 4.0.24. Die Fehlermeldungen begannen erst 17 Stunden nach dem Start des Adapters. 
Zusätzlich habe ich noch Warnmeldungen, diese begannen 75 Minuten nach dem Start des Adapters:

I have the same error messages, same system, but JS-Controller 4.0.24. However, the error messages began 17 hours after starting the adapter. 
In addition, I have warning messages that began 75 minutes after starting the adapter:

warn: eusec.0 (109721) Heartbeat check failed for station T8410xxxxxxxxxxxx. Connection seems lost. Try to reconnect...
warn: eusec.0 (109721) Tried all hosts, no connection could be established to station T8410xxxxxxxxxxxxx.

**Comment by locito09** [comment] 2023-09-25 11:05
habe den gleichen fehler immer wen die Kamera eine Bewegung erkennt, habe nun den Adapter ausgeschalet

**Comment by beandi** [comment] 2023-10-02 14:22
Habe den selben Fehler, bei mir genau alle 9min59sec.

**Comment by diablolot** [comment] 2023-10-06 06:59
Ich habe folgenden Fehler, erfolgt alle 5 Minuten. Ich hoffe sehr, dass wir es lösen können.

eusec.0 | 2023-10-06 08:54:04.532 | error | Station: T8030P2323201932 command CMD_SDINFO_EX failed with error: undefined (-148)
-- | -- | -- | --
eusec.0 | 2023-10-06 08:49:03.657 | error | Station: T8030P2323201932 command CMD_SDINFO_EX failed with error: undefined (-148)
eusec.0 | 2023-10-06 08:44:02.912 | error | Station: T8030P2323201932 command CMD_SDINFO_EX failed with error: undefined (-148)
eusec.0 | 2023-10-06 08:39:02.144 | error | Station: T8030P2323201932 command CMD_SDINFO_EX failed with error: undefined (-148)
eusec.0 | 2023-10-06 08:34:01.455 | error | Station: T8030P2323201932 command CMD_SDINFO_EX failed with error: undefined (-148)

**Comment by freakyfreaky** [comment] 2023-10-09 19:21
Same here
Station: T8030P2xxxxxx9 command CMD_SDINFO_EX failed with error: undefined (-148)

**Comment by andispammonyer** [comment] 2023-10-12 17:57
Same for me

**Comment by kilozwo** [comment] 2023-10-17 20:24
eusec.0 | 2023-10-17 22:22:30.142 | error | Station: T8030xxxxxxxxxxx command CMD_SDINFO_EX failed with error: undefined (-148)

every one minute.

**Comment by GM-Jokemaster** [comment] 2023-10-29 08:53
Same here

Station: T8030xxxxx command CMD_SDINFO_EX failed with error: undefined (-148)

**Comment by hohmannc85** [comment] 2023-11-01 05:24
same here!

2023-10-31 00:03:13.595  - [32minfo[39m: eusec.0 (304976) Disconnected from station T8200N0020280047
2023-10-31 00:03:13.805  - [32minfo[39m: eusec.0 (304976) Disconnected from station T8420N60210603E9
2023-10-31 00:03:13.973  - [32minfo[39m: eusec.0 (304976) Disconnected from station T8030P2322510D57
2023-10-31 00:03:14.903  - [32minfo[39m: eusec.0 (304976) Disconnected from station T8420N60210600F0
2023-10-31 00:03:15.065  - [32minfo[39m: eusec.0 (304976) Disconnected from station T8420N60210605FB
2023-10-31 00:03:16.141  - [32minfo[39m: eusec.0 (304976) Disconnected from station T8420N6021060520
2023-10-31 00:03:16.511  - [32minfo[39m: eusec.0 (304976) Disconnected from station T8410P302125348B
2023-10-31 00:03:16.598  - [32minfo[39m: eusec.0 (304976) Disconnected from station T8420N6021040839
2023-10-31 00:03:16.773  - [32minfo[39m: eusec.0 (304976) Disconnected from station T8010N2321140408
2023-10-31 00:03:18.664  - [32minfo[39m: eusec.0 (304976) Connected to station T8200N0020280047 on host 192.168.188.25 and port 25957
2023-10-31 00:03:19.288  - [32minfo[39m: eusec.0 (304976) Connected to station T8030P2322510D57 on host 192.168.188.42 and port 10228
2023-10-31 00:03:19.976  - [32minfo[39m: eusec.0 (304976) Connected to station T8420N60210600F0 on host 192.168.188.82 and port 22782
2023-10-31 00:03:20.112  - [32minfo[39m: eusec.0 (304976) Connected to station T8420N60210605FB on host 192.168.188.117 and port 10498
2023-10-31 00:03:20.136  - [32minfo[39m: eusec.0 (304976) Connected to station T8410P302125348B on host 192.168.188.111 and port 28935
2023-10-31 00:03:20.344  - [32minfo[39m: eusec.0 (304976) State value to set for "eusec.0.T8200N0020280047.cameras.T8200N0020280047.picture" has to be stringified but received type "object"
2023-10-31 00:03:20.351  - [32minfo[39m: eusec.0 (304976) Disconnected from station T8410P302125348B
2023-10-31 00:03:20.502  - [32minfo[39m: eusec.0 (304976) State value to set for "eusec.0.T8030P2322510D57.cameras.T8142N6321054E81.picture" has to be stringified but received type "object"
2023-10-31 00:03:20.686  - [31merror[39m: eusec.0 (304976) Station: T8030P2322510D57 command CMD_SDINFO_EX failed with error: undefined (-148)
2023-10-31 00:03:20.733  - [32minfo[39m: eusec.0 (304976) Connected to station T8010N2321140408 on host 192.168.188.150 and port 18903
2023-10-31 00:03:20.782  - [31merror[39m: eusec.0 (304976) Station: T8030P2322510D57 command CMD_SDINFO_EX failed with error: undefined (-148)
2023-10-31 00:03:20.829  - [32minfo[39m: eusec.0 (304976) State value to set for "eusec.0.T8420N60210600F0.cameras.T8420N60210600F0.picture" has to be stringified but received type "object"
2023-10-31 00:03:20.999  - [32minfo[39m: eusec.0 (304976) Connected to station T8420N6021060520 on host 192.168.188.84 and port 29585
2023-10-31 00:03:21.239  - [32minfo[39m: eusec.0 (304976) Connected to station T8410P302125348B on host 192.168.188.111 and port 22232
2023-10-31 00:03:21.367  - [31merror[39m: eusec.0 (304976) Station: T8030P2322510D57 command CMD_SDINFO_EX failed with error: undefined (-148)
2023-10-31 00:03:21.371  - [32minfo[39m: eusec.0 (304976) Connected to station T8420N6021040839 on host 192.168.188.86 and port 24304
2023-10-31 00:03:21.712  - [32minfo[39m: eusec.0 (304976) State value to set for "eusec.0.T8420N6021060520.cameras.T8420N6021060520.picture" has to be stringified but received type "object"
2023-10-31 00:03:21.836  - [32minfo[39m: eusec.0 (304976) State value to set for "eusec.0.T8010N2321140408.cameras.T8142N6321122F09.picture" has to be stringified but received type "object"
2023-10-31 00:03:21.862  - [32minfo[39m: eusec.0 (304976) State value to set for "eusec.0.T8010N2321140408.cameras.T8142N63211236C0.picture" has to be stringified but received type "object"
2023-10-31 00:03:21.899  - [32minfo[39m: eusec.0 (304976) State value to set for "eusec.0.T8410P302125348B.cameras.T8410P302125348B.picture" has to be stringified but received type "object"
2023-10-31 00:03:22.019  - [31merror[39m: eusec.0 (304976) Station: T8030P2322510D57 command CMD_SDINFO_EX failed with error: undefined (-148)
2023-10-31 00:03:22.026  - [31merror[39m: eusec.0 (304976) Station: T8030P2322510D57 command CMD_SDINFO_EX failed with error: undefined (-148)
2023-10-31 00:03:22.228  - [31merror[39m: eusec.0 (304976) Station: T8030P2322510D57 command CMD_SDINFO_EX failed with error: undefined (-148)
2023-10-31 00:03:27.597  - [32minfo[39m: eusec.0 (304976) State value to set for "eusec.0.T8420N6021040839.cameras.T8420N6021040839.picture" has to be stringified but received type "object"

**Comment by Stefan200583** [comment] 2023-11-04 14:32
Same error here

**Comment by sansonifabio** [comment] 2023-11-04 21:15
**Hallo @bropat auch unter der neuen Version v1.2.1 immer noch da selbe Problem.** 
Sobald man zum  Beispiel am Handy mit der Eufy App einen Livestream, öffnet kommen die Fehler:

Hello @bropat still having the same problem under the new version v1.2.1.**
For example, as soon as you open a live stream on your cell phone with the Eufy app, the errors appear



eusec.0
2023-11-04 22:09:04.154	error	Station: T8030P232242039F command CMD_SDINFO_EX failed with error: undefined (-148)

eusec.0
2023-11-04 22:09:04.151	error	Station: T8030P232245105A command CMD_SDINFO_EX failed with error: undefined (-148)

eusec.0
2023-11-04 22:09:04.149	error	Station: T8030P23224511EB command CMD_SDINFO_EX failed with error: undefined (-148)

eusec.0
2023-11-04 22:09:04.146	error	Station: T8030P2322481D9C command CMD_SDINFO_EX failed with error: undefined (-148)

eusec.0
2023-11-04 22:09:03.934	error	Station: T8030P232245105A command CMD_SDINFO_EX failed with error: undefined (-148)

eusec.0
2023-11-04 22:09:03.933	error	Station: T8030P2322481D9C command CMD_SDINFO_EX failed with error: undefined (-148)

eusec.0
2023-11-04 22:09:03.932	error	Station: T8030P232242039F command CMD_SDINFO_EX failed with error: undefined (-148)

eusec.0
2023-11-04 22:09:03.931	error	Station: T8030P23224511EB command CMD_SDINFO_EX failed with error: undefined (-148)

eusec.0
2023-11-04 22:09:03.764	error	Station: T8030P2322481D9C command CMD_SDINFO_EX failed with error: undefined (-148)

eusec.0
2023-11-04 22:09:03.762	error	Station: T8030P23224511EB command CMD_SDINFO_EX failed with error: undefined (-148)

eusec.0
2023-11-04 22:09:03.760	error	Station: T8030P232242039F command CMD_SDINFO_EX failed with error: undefined (-148)

eusec.0
2023-11-04 22:09:03.757	error	Station: T8030P232245105A command CMD_SDINFO_EX failed with error: undefined (-148)
``

**Comment by sansonifabio** [comment] 2023-11-05 09:36
Hallo @bropat ich denke das Probelm liegt in der Abfrage der SD Karten Info und hat damit zu tun falls man eine SSD in eine homebase s380 verbaut hat. Bei mir bleiben die drei Datenpunkte im Eusec Adapter unter Station immer leer. 
Bei einer Indoor Kamera die über eine SD Karte verfügt werden die Infos in die Datenpunkte geschrieben.

Herzliche Grüße
Fabio

Hello @bropat I think the problem lies in the query for the SD card information and has to do with it if you have installed an SSD in a homebase s380. For me, the three data points in the Eusec adapter under station always remain empty.
With an indoor camera that has an SD card, the information is written to the data points.

Best regards
Fabio

**Comment by bropat** [comment] 2023-11-05 10:57
Hello @sansonifabio,
unfortunately I don't have a homebase s380 and so I can't reproduce this problem. Furthermore, this part was not implemented by me.
The storage space is queried via the polling interval. If you make any interactions via the Eufy app and there is a P2P connection from the adapter to this device, it seems as if the adapter also receives some responses from the P2P commands of the Eufy app.

**Comment by sansonifabio** [comment] 2023-11-05 12:30
Hallo @bropat vielen Dank für deine Antwort. Also es ist ja so das du die Datenpunkte im Eusec Adapter für SD anlegst. 
Bei einer normale Homebase oder Kamera mit SD Karte werden die auch befüllt. Nur nicht wenn du eine S380 mit SSD hast dann bleiben die Datenpunkte leer. 
Das denke ich, sagt auch der Fehler aus das er keine Daten über die Anforderung erhält aber ich habe da keine Ahnung von, hier mal die Datenpunkte. Das erste Foto ist von einer InDoorcam mit SD Karte. Das zweite Foto von einer S380 mit SSD.
Die Fehler Meldungen betreffen bei mir auch nur meine S380 Stations. Könnte man eine Version machen wo das abholen der SD Datenpunkte unterbunden wird?

![Zwischenablage02](https://github.com/bropat/ioBroker.eusec/assets/88761140/1a56f813-ef45-496d-8afe-b4c2a625a1b1)
![Zwischenablage01](https://github.com/bropat/ioBroker.eusec/assets/88761140/ecc9367c-8563-498e-8436-22abb2aaae8a)

Und ja der Fehler tritt auch auf wenn man die Eufy App öffnet und sich einen Livestream anaschaut oder Aufnahmen löscht.

Kann ich irgendwie helfen?
Herzliche grüße
Fabio

Hello @bropat, thank you very much for your answer. So it's like that you create the data points in the Eusec adapter for SD.
With a normal home base or camera with an SD card, these are also filled. Only not if you have an S380 with SSD then the data points remain empty.
I think that's what the error says: it doesn't receive any data about the request, but I have no idea about the data points here. 
The error messages only affect my S380 stations. Could you make a version where the retrieval of SD data points is prevented?
The first photo from an inDoorcam with SD cards. The second photo of an S380 with SSD

![Clipboard02](https://github.com/bropat/ioBroker.eusec/assets/88761140/1a56f813-ef45-496d-8afe-b4c2a625a1b1)
![Clipboard01](https://github.com/bropat/ioBroker.eusec/assets/88761140/ecc9367c-8563-498e-8436-22abb2aaae8a)

And yes, the error also occurs when you open the Eufy app and watch a live stream or delete recordings.

Can I help you?
Best regards
Fabio

**Comment by bropat** [comment] 2023-11-05 16:25
I can try to look at the problem, but for that I need access to a Homebase S380. If you are willing to share it with me, I can try to isolate the problem.

**Comment by sansonifabio** [comment] 2023-11-05 17:42
Ich brauche deine Emailadresse um dich einzuladen.

**Comment by PhilippEngler** [comment] 2023-11-05 18:02
All what I can say is that since the update to version 3.x of HomeBase firmware (2 and 3), the retrieving of storage info is not working anymore.
I have seen in the app, that there are new objects (StorageInfo, EmmcInfo and HddInfo), which should contain the wanted values but I was not able to find the command they used to populate these objects.

**Comment by sansonifabio** [comment] 2023-11-07 05:31
> I can try to look at the problem, but for that I need access to a Homebase S380. If you are willing to share it with me, I can try to isolate the problem.

@bropat  We can do that, but I need an email address from you. Would it be possible to release a version where you can deactivate the log? Because these error messages flood the log file.
Greetings Fabio

**Comment by bropat** [comment] 2023-11-07 16:15
@sansonifabio 

I'll get back to you as soon as I have time.

**Comment by sansonifabio** [comment] 2023-11-07 16:25
Okay 👍

**Comment by PhilippEngler** [comment] 2023-11-07 17:08
I have removed the storage info gathering for the HomeBases and created a pull request. For the T8410 the storage info is gathered correctly.

**Comment by sansonifabio** [comment] 2023-11-07 20:38
Hello @PhilippEngler, I'm not a programmer, just a user, could you briefly explain what you did?
Greetings
Fabio


Hallo @PhilippEngler ich bin kein Programmierer sondern nur User, könntest du kurz erklären was du gemacht hast?
Grüße
Fabio

**Comment by PhilippEngler** [comment] 2023-11-08 07:40
Hello @sansonifabio, I have changed the capability of the HomeBases so that the storage information should not be gathered anymore for these devices. At the moment, the behaviour has not changed, it is nessessary to release a new version of the client and a new version of the ioBroker addon.

Best, Philipp

**Comment by sansonifabio** [comment] 2023-11-08 08:16
@PhilippEngler Thanks, that sounds very good. This means that when @bropat has time, a new version will be released and the errors will be gone. Now my logs are completely overflowing because I have 4 home bases and I have to pause the adapter during the day.

Greetings
Fabio

@PhilippEngler Danke, das hört sich ja sehr gut an. Das bedeutet, das wenn @bropat Zeit hat dann eine neue Version veröffentlicht und dadurch die Fehler weg sind. Jetzt ist das so  bei mir die Logs völlig überlaufen da ich 4 Homebase habe tagsüber muss ich den Adapter pausieren.

Grüße
Fabio

**Comment by sansonifabio** [comment] 2023-11-08 15:42
> @sansonifabio
> 
> I'll get back to you as soon as I have time.

Hier noch eien paar Logs:
`eusec.0

2023-11-08 16:35:50.585	debug	[P2PClientProtocol.handleData] Handle DATA DATA - Result data received - Detecting correct sequence number [{"stationSN":"T8410P422302BC3B","commandIdName":"CMD_SDINFO_EX","commandId":1144,"seqNumber":6,"newSeqNumber":7,"p2pSeqMappingCount":0}]

eusec.0

2023-11-08 16:35:50.585	debug	[P2PClientProtocol.handleData] Handle DATA DATA - Received data [{"stationSN":"T8410P422302BC3B","commandIdName":"CMD_SDINFO_EX","commandId":1144,"resultCodeName":"ERROR_PPCS_SUCCESSFUL","resultCode":0,"resultData":"11750000c3740000","data":"0000000011750000c3740000","seqNumber":8,"p2pDataSeqNumber":7,"offsetDataSeqNumber":0}]

eusec.0

2023-11-08 16:35:50.576	debug	[P2PClientProtocol.handleData] Handle DATA DATA - Result data received - Detecting correct sequence number [{"stationSN":"T8410P422302BC3B","commandIdName":"CMD_SDINFO_EX","commandId":1144,"seqNumber":5,"newSeqNumber":6,"p2pSeqMappingCount":1}]

eusec.0

2023-11-08 16:35:50.576	debug	[P2PClientProtocol.handleData] Handle DATA DATA - Received data [{"stationSN":"T8410P422302BC3B","commandIdName":"CMD_SDINFO_EX","commandId":1144,"resultCodeName":"ERROR_PPCS_SUCCESSFUL","resultCode":0,"resultData":"11750000c3740000","data":"0000000011750000c3740000","seqNumber":8,"p2pDataSeqNumber":7,"offsetDataSeqNumber":0}]`

**Comment by PhilippEngler** [comment] 2023-11-08 15:53
@sansonifabio: You also have these problems also with the T8410? Do you see the free and used values and are they the same as in the App? If not, which firmwareversion is your T8410 on?

**Comment by sansonifabio** [comment] 2023-11-08 16:01
@PhilippEngler  only have problems with the S380 as no values ​​are displayed in the adapter. The data on the indoor camera T8410 is the same because the camera used an SD card but I installed SSD disks in my S380.

Ich habe die Probleme nur mit der Station S380 da werden auch keine Werte der SD im Adapter angezeigt. 
Bei der Indoorcam sind die die Daten im Adapter gleich weil die Kamera ja eine SD Karte benutzte ich aber in meinem S380 SSD Platten verbaut habe.

**Comment by bropat** [comment] 2023-11-12 10:35
@sansonifabio 

You can share the station to this account:           patrick.broetto+eu1@gmail.com

**Comment by bropat** [comment] 2023-11-12 10:48
Short update:

Eufy has changed the P2P command `CMD_SDINFO_EX` (which is not only valid for SD cards, but for the memory in general) from a certain firmware version. At first only how the result of the command was transmitted and now also how the command for the stations (at least the Homebase 2; Homebase 3 I have to check first) must be sent.
For the first part, everything has already been implemented in [this commit](https://github.com/bropat/eufy-security-client/commit/f16afecf3b73bdb8c429e55c55db844366f20054#diff-d80462ba92570b474232f56e11b30f864095567e262d0c9416c9eb694409d19a). For details [see here](https://github.com/bropat/eufy-security-client/blob/516a79ea756971aa2d7fef89cd9564303fce995a/src/p2p/session.ts#L1318-L1324).
For the second part, I have already adapted the command for Homebase 2 and it works.
For Homebase 3 I am waiting for the sharing of @sansonifabio.

Expected code change to support Homebase 2 and Homebase3:
```typescript
    public getStorageInfoEx(): void {
        this.log.debug(`Station send get storage info command`, { stationSN: this.getSerial() });
        if (this.isStation() && isGreaterEqualMinVersion("3.3.0.0", this.getSoftwareVersion())) {
            this.p2pSession.sendCommandWithoutData(CommandType.CMD_SDINFO_EX, Station.CHANNEL);
        } else {
            this.p2pSession.sendCommandWithIntString({
                commandType: CommandType.CMD_SDINFO_EX,
                value: 0,
                valueSub: 0,
                channel: 255,
                strValue: this.rawStation.member.admin_user_id
            });
        }
    }
```

**Comment by sansonifabio** [comment] 2023-11-12 10:54
> @sansonifabio
> 
> You can share the station to this account: [patrick.broetto+eu1@gmail.com](mailto:patrick.broetto+eu1@gmail.com)

@bropat  Invitation is out

**Comment by bropat** [comment] 2023-11-12 11:08
The command for Homebase 3 is different:

`CMD_SET_PAYLOAD` with this parameters:

```json
{
   "account_id":"<REDACTED>",
   "cmd":1307,
   "mChannel":0,
   "mValue3":0,
   "payload":{
      "version":0.0,
      "cmd":11001.0
   }
}
```

Response:

```json
{
   "cmd":1307,
   "payload":{
      "cmd":11001,
      "version":127,
      "mIntRet":0,
      "msg":"",
      "old_storage_label":"",
      "cur_storage_label":"",
      "body":{
         "body_version":1,
         "storage_days":1,
         "storage_events":2,
         "con_video_hours":0,
         "format_transaction":"",
         "format_errcode":0,
         "hdd_info":{
            "serial_number":"<REDACTED>",
            "disk_path":"/dev/sda",
            "disk_size":1048576,
            "system_size":2099,
            "disk_used":45689,
            "video_used":4,
            "video_size":900654,
            "cur_temperate":27,
            "parted_status":1,
            "work_status":0,
            "hdd_label":"hdd_9A815F3ACC822B1BD17AE9F740D085F1",
            "health":0,
            "device_module":"CT1000MX500SSD1",
            "hdd_type":1
         },
         "move_disk_info":{
            "disk_path":"",
            "disk_size":0,
            "disk_used":0,
            "part_layout_arr":[
               
            ],
            "data":[
               
            ]
         },
         "emmc_info":{
            "disk_nominal":0,
            "disk_size":15974,
            "system_size":3158,
            "disk_used":2792,
            "data_used_percent":18,
            "swap_size":2048,
            "video_size":10435,
            "video_used":6,
            "data_partition_size":12816,
            "eol_percent":0,
            "work_status":0,
            "health":0
         }
      }
   }
}
```

I first have to re-implement everything for this.

**Comment by sansonifabio** [comment] 2023-11-12 11:15
> I first have to re-implement everything for this.

Wow @bropat

**Comment by bropat** [comment] 2023-11-12 11:40
> Short update:
> 
> Eufy has changed the P2P command `CMD_SDINFO_EX` (which is not only valid for SD cards, but for the memory in general) from a certain firmware version. At first only how the result of the command was transmitted and now also how the command for the stations (at least the Homebase 2; Homebase 3 I have to check first) must be sent. For the first part, everything has already been implemented in [this commit](https://github.com/bropat/eufy-security-client/commit/f16afecf3b73bdb8c429e55c55db844366f20054#diff-d80462ba92570b474232f56e11b30f864095567e262d0c9416c9eb694409d19a). For details [see here](https://github.com/bropat/eufy-security-client/blob/516a79ea756971aa2d7fef89cd9564303fce995a/src/p2p/session.ts#L1318-L1324). For the second part, I have already adapted the command for Homebase 2 and it works. For Homebase 3 I am waiting for the sharing of @sansonifabio.
> 
> Expected code change to support Homebase 2 and Homebase3:
> 
> ```ts
>     public getStorageInfoEx(): void {
>         this.log.debug(`Station send get storage info command`, { stationSN: this.getSerial() });
>         if (this.isStation() && isGreaterEqualMinVersion("3.3.0.0", this.getSoftwareVersion())) {
>             this.p2pSession.sendCommandWithoutData(CommandType.CMD_SDINFO_EX, Station.CHANNEL);
>         } else {
>             this.p2pSession.sendCommandWithIntString({
>                 commandType: CommandType.CMD_SDINFO_EX,
>                 value: 0,
>                 valueSub: 0,
>                 channel: Station.CHANNEL,
>                 strValue: this.rawStation.member.admin_user_id
>             });
>         }
>     }
> ```

I have also tested the code suggested above with the Homebase3 and it works without me having to implement the "new interface".  ;)

**Comment by bropat** [comment] 2023-11-12 11:41
I get the following values:

```
sdCapacity: 12816
sdCapacityAvailable: 10024
```

**Comment by bropat** [comment] 2023-11-12 11:42
These are the values of the integrated memory (EMMC).

**Comment by bropat** [comment] 2023-11-12 11:43
To make the values of the SSD (extended memory) available, I must of course implement the new interface.

**Comment by sansonifabio** [comment] 2023-11-12 11:45
> Um die Werte der SSD (Extended Memory) verfügbar zu machen, muss ich natürlich die neue Schnittstelle implementieren.

@bropat Thank you very much for the information and your endless effort, I'm really happy that you managed it.

**Comment by bropat** [comment] 2023-11-12 11:49
[See also here](https://github.com/bropat/eufy-security-client/issues/380).

**Comment by bropat** [comment] 2023-11-12 11:52
Created feature request: [[Feature request]: Support HB3 extended storage](https://github.com/bropat/eufy-security-client/issues/403)

**Comment by bropat** [comment] 2023-11-12 11:56
@sansonifabio you can remove the sharing.

**Comment by sansonifabio** [comment] 2023-11-12 12:29
Hello @bropat , thank you very much for your help and I just deleted the share.

**Comment by harryslapalot** [comment] 2023-12-20 10:53
Any estimate when the new version that has this fixed will be released?

**Comment by sansonifabio** [comment] 2024-02-08 04:43
Hello @bropat ,

I also ask, do you know when you will release the update? I now have 4 home bases and my ioBroker is full of hundreds of errors every day. I know you have a lot to do but it would be nice if you could do it in a timely manner.
Best regards
Fabio

Hallo @bropat ,

auch von mir die Frage ob du weißt du wann du das Update freigibst? 
Ich habe mittlerweile 4  Homebase und mein ioBroker läuft jeden Tag mit hunderten Errors voll. 
Ich weiß das du viel zu tun hast, aber es wäre wirklich sehr schön wenn du es Zeitnah schaffen könntest.

Herzliche Grüße und vielen Dank
Fabio

**Comment by GM-Jokemaster** [comment] 2024-02-09 08:43
Also, and yes i know you said don't ask for a Time...
Im sorry but please fix it soon ...

**Comment by bropat** [comment] 2024-02-09 13:23
The prerequisite for a new release is reaching the milestone `3.0.0` in the `eufy-security-client` project, which I am currently working on.

**Comment by sansonifabio** [comment] 2024-02-09 14:05
Hello @bropat thank you very much for your answer.
Greetings
Fabio


Hallo @bropat vielen Dank für deine Antwort.
Herzliche Grüße
Fabio

**Comment by ges7881** [comment] 2024-03-06 06:51
Hallo,
gibt es eine Möglichkeit die Fehlermeldung zu unterdrücken, bzw. die Meldungen des ganzen Adapters abzuschalten bis das Update bereit stehen wird? 

Danke im Voraus und beste Grüße
Gessy

**Comment by lenusch** [comment] 2024-03-07 16:45
Same Problems here. Thx for your Work. i will try to be patient :-)

**Comment by Uli977** [comment] 2024-03-15 11:55
> Hallo, gibt es eine Möglichkeit die Fehlermeldung zu unterdrücken, bzw. die Meldungen des ganzen Adapters abzuschalten bis das Update bereit stehen wird?
> 
> Danke im Voraus und beste Grüße Gessy

Das würde mich auch interessieren.

**Comment by xanthos84** [comment] 2024-04-07 08:18
eufy-security-client 3.0 was released in march...
when do you think can you update eusec to newest client to fix this bug?

**Comment by Captain-patty** [comment] 2024-04-12 11:13
Any news on upcoming release of new eusec version?

Tahnk you!

**Comment by Uli977** [comment] 2024-05-31 08:01
Moin! Gibt es einen Fortschritt zu melden?
Hunderte Fehlermeldungen pro Tag sind wirklich anstrengend auf Dauer.

**Comment by GreatEMU** [comment] 2024-07-12 06:57
Auch Mitte Juli warten wir auf ein Update...

**Closed** 2024-08-27 18:02 UTC
Labels: bug, fixed

**Comment by andiweli** [comment] 2024-09-27 23:55
Aktuell wieder dieser Fehler:

command CMD_SDINFO_EX failed with error
